env: "local" #local, dev, prod
storage_path: "postgres://user:password@postgres:5432/app?sslmode=disable"
http_server:
  port: ":8080"
  timeout: 300ms
  idle_timeout: 60s
  graceful_shutdown_time_out: 3600s